# Site settings
title: 
header-img: img/home-bg.png
email: jimlotruglio@yahoo.com
copyright_name: jimjim698
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jimjim698
learn_profile: jimjim698
email_username: jimlotruglio@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
