# Site settings
author: Jim Lotruglio
title: Code and Behold
header-img: img/home-bg.png
email: jimlotruglio@yahoo.com
copyright_name: Jim Lotruglio
description: > # this means to ignore newlines until "baseurl:"
  Late bloomer into tech starting at the age of 27.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jimjim698

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
